# This workflows runs your tests as specified in your .smalltalk.ston configuration file.

name: Run tests

on:
  push:
    branches: [ "master" ] # By default, your default branch.
 
jobs:
  uses: moosetechnology/.github/.github/workflows/run-tests.yml
